### ISSUE TITLE
how to depend audio file duration and frame_size and step

### ISSUE THREAD

**Issue by hirunifernando** [tyiannak/multimodalAnalysis#1]
Hi Tyiannal,

frame_size =0.050
step=0.025
[Fs, x] = audioBasicIO.readAudioFile("sample.wav");
F, f_names = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);

I want to create a cnn model to predict human emotion from the audio file. To train the model I m using the different duration of audio files, since should I need to modify frame_size and step.
Can u explain how audio duration and frame_size and step depend on each other?

Thank u

**Comment by tyiannak** [comment]
I suppose you mean you want to provide stFeatureExtraction with such a.sort-term step so that the size of F is constant, regardless of the respective signal's duration right?
I think that a better solution is to use static frame size/step and then crop/resize the output feature matrix before feeding it to the CNN.

**Comment by hirunifernando** [comment]
Thank u very much tyiannakk
